### ISSUE TITLE
proposal(docs): add instructions to add code for eth precision 

### ISSUE THREAD

**Issue by p0mvn** [Jeiwan/uniswapv3-book#15]
**Context**

The code instructions from https://uniswapv3book.com/docs/milestone_1/calculating-liquidity/ are missing:
```
eth = 10**18
....
amount_eth = 1 * eth
amount_usdc = 5000 * eth
```

While I could look in [this repo](https://github.com/Jeiwan/uniswapv3-code) for the answer, it wasn't apparent with high certainty why my calculations weren't working.

Therefore, I propose adding the above code snippets to the linked page for a better UX.

**Comment by Jeiwan** [comment]
Fixed: https://github.com/Jeiwan/uniswapv3-book/commit/7ded3c1084441cf8034665e2ff1ecf381104a1cf
