### ISSUE TITLE
Addition of event mint is missing

### ISSUE THREAD

**Issue by shubhank-saxena** [Jeiwan/uniswapv3-book#25]
Hello!
While following the miltestone_1 (https://uniswapv3book.com/docs/milestone_1/providing-liquidity/), at the end of the mint, we are expected to emit an event mint to inform the blockchain.
However, in the above code snippets/explanation, the declaration of the said event is missing.
```
    event Mint(
        address sender,
        address indexed owner,
        int24 indexed tickLower,
        int24 indexed tickUpper,
        uint128 amount,
        uint256 amount0,
        uint256 amount1
    );
    ```

**Comment by Jeiwan** [comment]
In the code snippets I omit a lot of stuff that's not directly related to the concepts explained. Events is not something that affects the logic of the contracts, thus they're omitted. In the code, all events are in place:
https://github.com/Jeiwan/uniswapv3-code/blob/main/src/UniswapV3Pool.sol#L303-L311

**Comment by shubhank-saxena** [comment]
Oh, I see. I thought it was left by mistake. Thank you for such an amazing book ❤️
