### ISSUE TITLE
Ask for permission to translate this book into Chinese

### ISSUE THREAD

**Issue by y1cunhui** [Jeiwan/uniswapv3-book#3]
I really love this book and want to promote it to the Chinese community. May I translate it into Chinese (of course after your proofreading)

**Comment by Jeiwan** [comment]
Permission granted 🙂

Let me know when it's done so I could add links.

**Comment by y1cunhui** [comment]
Thx~

**Comment by y1cunhui** [comment]
BTW, would you mind adding the command of building this book into README? So that I cound write and test it locally. @Jeiwan

**Comment by Jeiwan** [comment]
@y1cunhui 
Done: https://github.com/Jeiwan/uniswapv3-book#running-locally 😉
