### ISSUE TITLE
shouldTransferInCallback in setupTestCase should become before pool.mint()

### ISSUE THREAD

**Issue by Zarfsec** [Jeiwan/uniswapv3-book#40]
In the following snippet, shouldTransferInCallback should be set before `pool.mint()` https://github.com/Jeiwan/uniswapv3-book/blob/7b6cc62c9d1ffb7e775c90fbe60f0293b48f539d/content/docs/milestone_1/providing-liquidity.md?plain=1#L459-L485.

Otherwise the callback will not send the funds from the test contract to the pool contract and the assertions will fail.

**Comment by Jeiwan** [comment]
The flag is not used during a pool setup. It's using to imitate failures in minting and swapping during testing:
- https://github.com/Jeiwan/uniswapv3-code/blob/milestone_1/test/UniswapV3Pool.t.sol#L140-L153
- https://github.com/Jeiwan/uniswapv3-code/blob/milestone_1/test/UniswapV3Pool.t.sol#L237-L243
