### ISSUE TITLE
how to automatic calculate token1 amount from token 0 amount and the ticks

### ISSUE THREAD

**Issue by vvsuperman** [Jeiwan/uniswapv3-book#42]
great jobs! In uniswap after we finished setting price range, the ui can calculate token1 amount from token0 amount we input, how did that happan? I have searched in your ui source code but not found that
![image](https://user-images.githubusercontent.com/7919221/205491117-a9f04f35-fda3-45ab-8db9-a1d0aae0bb66.png)

**Comment by Jeiwan** [comment]
It uses the Quoter contract I guess:
https://github.com/Uniswap/v3-sdk/blob/main/src/quoter.ts#L51

Yeah, I don't have this implemented in the UI, but I have the Quoter contract:
https://github.com/Jeiwan/uniswapv3-code/blob/main/src/UniswapV3Quoter.sol#L26
