### ISSUE TITLE
Question about tick feeGrowthOutsideX128{0,1} initialization

### ISSUE THREAD

**Issue by LoganAtCrypto** [Jeiwan/uniswapv3-book#45]
hi @Jeiwan, thanks for the great book! 

After dived into the book and the source code, i still can't figure out why `tick.feeGrowthOutside0X128` and `tick.feeGrowthOutside1X128` are initialized as follows:

```solidity
    function update(
        mapping(int24 => Tick.Info) storage self,
        int24 tick,
        int24 tickCurrent,
        int128 liquidityDelta,
        uint256 feeGrowthGlobal0X128,
        uint256 feeGrowthGlobal1X128,
        uint160 secondsPerLiquidityCumulativeX128,
        int56 tickCumulative,
        uint32 time,
        bool upper,
        uint128 maxLiquidity
    ) internal returns (bool flipped) {
       // ......
        if (liquidityGrossBefore == 0) {
            // by convention, we assume that all growth before a tick was initialized happened _below_ the tick
            if (tick <= tickCurrent) {
                info.feeGrowthOutside0X128 = feeGrowthGlobal0X128;
                info.feeGrowthOutside1X128 = feeGrowthGlobal1X128;
                info.secondsPerLiquidityOutsideX128 = secondsPerLiquidityCumulativeX128;
                info.tickCumulativeOutside = tickCumulative;
                info.secondsOutside = time;
            }
            info.initialized = true;
        }
       // ......
    }
```

**Uniswap V3 whitepaper section 6**

<img width="487" alt="whitepaper" src="https://user-images.githubusercontent.com/80801525/208571356-c451d638-71db-4d63-b7e9-2a23cb2b97f9.png">

![fees](https://user-images.githubusercontent.com/80801525/208571432-96d4a3da-f618-43ca-ad94-100e7a4da59d.png)

i tried to verify the swap fee accumulating  process in my head, everything goes well until new ticks are initialized. 

I must have misunderstood something!

thank you!

**Comment by Jeiwan** [comment]
This is tricky :)
I see what you mean.

**Comment by Jeiwan** [comment]
This is tricky :)

I see what you mean. It should revert if a new position includes an initialized upper tick with some accrued fees and the lower tick is not initialized. This needs to be tested in a forked environment, but I don't have enough time for this at the moment. Hopefully, later :)

**Comment by Jeiwan** [comment]
I figured it out. It's a known feature of Uniswap: https://github.com/Uniswap/v3-core/issues/573

`feeGrowthOutside0X128` and `feeGrowthGlobal1X128` do underflow in the situation you described. But this is not a bug because in fee calculations "fee growth" values are subtracted from the global ones. So it always ends up using the difference in fee growth, never actual values.

**Comment by LoganAtCrypto** [comment]
> I figured it out. It's a known feature of Uniswap: [Uniswap/v3-core#573](https://github.com/Uniswap/v3-core/issues/573)
> 
> `feeGrowthOutside0X128` and `feeGrowthGlobal1X128` do underflow in the situation you described. But this is not a bug because in fee calculations "fee growth" values are subtracted from the global ones. So it always ends up using the difference in fee growth, never actual values.

thank you very much @Jeiwan, finally, figured it out! ❤️

**Comment by logan-xyz** [comment]
The formula/code is very smart. it relies on the solidity underflow/overflow. the magical is that even with underflow/overflow, you can still got the correct fee owned by the position: `position. tokensOwed{0,1} =  feeGrowthInside{0,1}X128  - position. feeGrowthInside{0,1}LastX128`.

it's really magic/tricky to me! I worked very hard to figure this out!
