### ISSUE TITLE
Correct Price Range

### ISSUE THREAD

**Issue by juroberttyb** [Jeiwan/uniswapv3-book#49]
In the bottom of [this page](https://uniswapv3book.com/docs/introduction/uniswap-v3/), price range should be corrected from [ $2^{-128}$, $2^{128}$ ] to ( $2^{-128}$, $2^{128}$ )

If I understand correctly, since $\sqrt{P}$ is expressed as a fixed point Q64.96 number, the actual price P could not be exactly $2^{-128}$ nor $2^{128}$ by nature of floating point numbers.

(Edit for correct math expression.)

**Comment by Jeiwan** [comment]
As you said, Q64.96 is a fixed point number, not a floating point one. So I don't see why it cannot be either $2^{128}$ or $2^{-128}$.

**Comment by juroberttyb** [comment]
Coming back after two years, sorry for being late.

Say we would like to represent $2^{128}$.

Let $p(i) = 1.0001^{i}$

 $1.0001^{i} = 2^{128}$

 $i = log_{1.0001} 2^{128}$

 $i ~= 887272.44$

But since ticks are integers, $i$ is capped at $887272$.

So in my understanding, representing $2^{128}$ is not possible since

 $1.0001^{887272} < 1.0001^{887272.44} = 2^{128}$, where $1.0001^{887272}$ being the max price possible to be represented using ticks and Q64.96.
