### ISSUE TITLE
An error in calculation

### ISSUE THREAD

**Issue by laurivil** [Jeiwan/uniswapv3-book#52]
Hi, there seems to be an error in milestone1 first-swap.md. The calculation after this line is erroneous:
"Luckily, we already know all the values, so we can plug them in right away (this might not fit on your screen!):"

![image](https://user-images.githubusercontent.com/101333540/212044786-4ef9803f-b355-46e9-a133-c07ea7fad907.png)

![image](https://user-images.githubusercontent.com/101333540/212044375-73fc1234-d734-429d-ba32-c3c2c7c06d6b.png)

**Comment by Jeiwan** [comment]
`5602277097478614198912276234240` and `5604469350942327889444743441197` are Q64.96 numbers, i.e. their base is $2^{96}$. The result shown in the book is a decimal number. To get the same result, you need to divide both number by $2^{96}$ before the calculation, or you can multiply the value you got by $2^{96}$.

I made this small fix to try to mitigate the confusion: https://github.com/Jeiwan/uniswapv3-book/commit/e1a115db8e46ed6d14aad0a60e45fa87aa723ee6
