### ISSUE TITLE
Tick spacing vs Fee for Uni V3 pool identification

### ISSUE THREAD

**Issue by zaqk** [Jeiwan/uniswapv3-book#53]
Thanks for uniswap v3 guide. It's extremely useful.

I noticed in your book you refer to the ticket spacing as being used for pool identification and path creation:
https://uniswapv3book.com/docs/milestone_4/path/

It seems like uniswap uses the fee to identify pools:
https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/PoolAddress.sol#L33

Am I reading this wrong or is this part of the docs off?

**Comment by Jeiwan** [comment]
I used tick spacing in Milestone 4 because fees are only implemented in Milestone 5. So, yeah, in Milestone 4, tick spacing is used as a part of pool IDs, and, in Milestone 5, it's updated to use fees:
https://github.com/Jeiwan/uniswapv3-code/blob/milestone_5/src/UniswapV3Factory.sol#L57

**Comment by zaqk** [comment]
Got it. It confused me. I got to the book from googling and assumed that tick spacing was used as part of pool identification for uniswap v3 based off what was written.
