### ISSUE TITLE
Clarify that the tick bitmap only indexes spaced ticks

### ISSUE THREAD

**Issue by imasters11** [Jeiwan/uniswapv3-book#75]
I have been using the v3 Book a lot recently and I really appreciate the effort put in.

I recently spend some time integrating the tick bitmap and tick bitmap lens, and I spent some time confused by the results I was getting from the queries. I was able to clarify my misunderstanding by looking at the tick lens code, but thought some clarification in the book might help others. The issue I had was the following:

I was trying to use the bitmap and the bitmap lens to find initialized ticks around the current price tick. I was taking the current tick from the `slot0` query and trying to find the associated word in the bitmap by integer dividing by 256; when I did this, I was always getting 0 for the bitmap result (no initialized ticks in word) even thought I knew there were initialized ticks around the current tick. In reality, the bitmap only indexes _spaced_ ticks (i.e. ticks evenly divisible by `tickSpacing`) and I had to first integer divide the current tick by `tickSpacing` before dividing by 256.

The `Tick Bitmap Index` page does a great job of explaining the bitmap, but since the explainer uses a tick spacing of 1, I think this step gets a little bit lost. Also, since the width of the tick index is 24 bits and the word index (16 bits) and bit array (8 bits) sum to that, I think it's easy to assume the bitmap is sparse. There is a disclaimer that the tick spacing is 1, but I think readers could benefit from an explanation that tick spacing must be collapsed to find the correct bitmap index. 

I am happy to give it a shot if the maintainers would prefer a pull request over an issue. Thanks for the good work!

**Comment by Jeiwan** [comment]
Great catch!

Fixed: https://github.com/Jeiwan/uniswapv3-book/commit/2ddcd1c625a84a7c06289182ae0b17a24d8e9fae
