### ISSUE TITLE
Calculating liquidity

### ISSUE THREAD

**Issue by rracinskij** [Jeiwan/uniswapv3-book#8]
Hello, thank you for a great work!

Could you please explain why are you multiplying the USDC amount by ETH decimals (10^18) in the line 58 of `unimath.py` example?

`amount_usdc = 5000 * eth`

And not by `10*(18-6)=10^12`?

I tested it on actual Uniswap position and the numbers matched with `10*12`.

**Comment by Jeiwan** [comment]
I'm using 18 decimals for USDC in the book for simplicity.
