### ISSUE TITLE
Create a pdf version

### ISSUE THREAD

**Issue by ilguardianodelblocco** [Jeiwan/uniswapv3-book#85]
As the title, is it possible to create a pdf version of this wonderful book?

Regards

**Comment by brianyang** [comment]
+1

**Comment by Jeiwan** [comment]
Yep, shouldn't be too hard to make. Will try to find time for that!

**Comment by brianyang** [comment]
i know this seems like grunt work, but it would be insanely useful to ingest the book with an LLM. hope you will find time to do this! 

https://github.com/RyanFitzgerald/ebook-generator

**Comment by ilguardianodelblocco** [comment]
> i know this seems like grunt work, but it would be insanely useful to ingest the book with an LLM. hope you will find time to do this!
> 
> https://github.com/RyanFitzgerald/ebook-generator

I tried, but I failed. The pdf is created but the images are not created and there are some impagination problems.
I have even resolved an issue about the .md files in different folders but it was not enough.

**Comment by Jeiwan** [comment]
Added a printable version: https://uniswapv3book.com/print.html
Can be saved to PDF from the browser.

Enjoy 😉
